name: Check

on:
  workflow_dispatch:
  # pull_request:
  # push:
  #   branches:
  #     - main

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run format_check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint_check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run build -w @motojouya/kniw-core
      - run: npm run test -ws --if-present

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run build -w @motojouya/kniw-command
      - name: check build diff
        run: |
          build_diff=$(git diff --name-only | wc -l)
          if [ "$build_diff" -ne 0 ]; then
            exit 1
          fi
